### ISSUE TITLE
Reafaktorisati kod!

### ISSUE THREAD

**Issue by gianthead97** [MATF-RS20/RS022-tebrafile#7]
Raspasce se sve u jednom momentu.

**Comment by jvn-mirkov** [comment]
ће изгинемо у код.

**Comment by gianthead97** [comment]
![](https://media3.giphy.com/media/l2YWFAihWiwENMvJe/giphy.gif?cid=790b7611106b30c7a7af9489810525f8297cc012ef31408d&rid=giphy.gif)
